start_time: "2026-06-14T12:00:00+00:00"
duration: 120
prep_minutes: 15
tick_length: 60
server: "http://localhost:8080"
site_folder: "site"
score_cap: 100
negative_score_cap: -50
successful_benign_points: 10
failed_benign_points: 5
successful_malicious_points: 15
failed_malicious_points: 8
down_points: 20
