"""initial_schema

Revision ID: 3fae0496a59c
Revises: 
Create Date: 2026-06-14 09:06:19.093415

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3fae0496a59c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('folder', sa.String(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('attacker_class', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('vulns', sa.Integer(), nullable=False),
    sa.Column('req_per_tick', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('bot_signing_key_pem', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_schedule_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        "target_id",
        "tick",
        "request_id",
        name="uq_target_schedule_entries_target_tick_request",
    )
    )
    op.create_table('tick_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'tick', name='uq_tick_submissions_team_tick')
    )
    op.create_table('attack_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tick_submission_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.ForeignKeyConstraint(['tick_submission_id'], ['tick_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        "tick_submission_id",
        "target_id",
        "request_id",
        name="uq_attack_records_submission_target_request",
    )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attack_records')
    op.drop_table('tick_submissions')
    op.drop_table('target_schedule_entries')
    op.drop_table('teams')
    op.drop_table('targets')
    # ### end Alembic commands ###
